ACS\ACSPanelSettingsBundle\Entity\ConfigSetting:
    type: mappedSuperclass
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        # identifier of the setting
        setting_key:
            type: string
            length: 255
            fixed: false
            nullable: false
        # config value could be anything
        value:
            type: text
            length: 255
            fixed: false
            nullable: false
        # if is user setting or system setting
        context:
            type: string
            length: 255
            fixed: false
            nullable: false
        # needed to organize the view of settings
        focus:
            type: string
            length: 255
            fixed: false
            nullable: false
        # Label to show
        label:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {}
