zaspanel_backup:
    resource: "@ACSACSPanelBackupBundle/Resources/config/routing.yml"
    prefix:   /

acs_settings:
    resource: "@ACSACSPanelSettingsBundle/Resources/config/routing.yml"
    prefix:   /

acs_acspanel:
    resource: "@ACSACSPanelBundle/Resources/config/routing.yml"
    prefix:   /

# Global search action
global_search:
    pattern:  /search
    defaults: { _controller: "ACSACSPanelBundle:Default:search" }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme
