domain:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:Domain:index" }

domain_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:Domain:show" }

domain_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:Domain:new" }

domain_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:Domain:create" }
    requirements: { _method: post }

domain_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:Domain:edit" }

domain_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:Domain:update" }
    requirements: { _method: post }

domain_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:Domain:delete" }
    requirements: { _method: post }

domain_setalias:
    pattern:  /{id}/setalias/{type}
    defaults: { _controller: "ACSACSPanelBundle:Domain:setalias" }

domain_setenabled:
    pattern: /{id}/setenabled
    defaults: { _controller: "ACSACSPanelBundle:Domain:setenabled" }
