ACS\ACSPanelBundle\Entity\IpAddress:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: ip
    properties:
        ip:
            - Ip:  { version: all }

ACS\ACSPanelBundle\Entity\MailMailbox:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [mail_domain, username]

ACS\ACSPanelBundle\Entity\Domain:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: domain
    properties:
        domain:
            - Regex:
                pattern: "/^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}$/"
                message: The domain must be valid domain name
            #- ACS\ACSPanelBundle\Validator\Constraints\DuplicateHost: 
                #target_entity: ACSACSPanelBundle:HttpdAlias
                #target_field: alias

ACS\ACSPanelBundle\Entity\FosUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: emailCanonical
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: usernameCanonical

ACS\ACSPanelBundle\Entity\DatabaseUser:
    constraints:
        - ACS\ACSPanelBundle\Validator\Constraints\VariableLimitedLength: 
            max_length: 16
